# Generated by Django 6.0.2 on 2026-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('mobile', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('earbuds', 'Earbuds / Headphones'), ('watch', 'Watch / Smartwatch'), ('wallet', 'Wallet / Purse'), ('bag', 'Bag'), ('id_card', 'ID Card / Certificate'), ('keys', 'Keys'), ('jewellery', 'Jewellery'), ('vehicle', 'Vehicle'), ('document', 'Document'), ('electronics', 'Other Electronics'), ('other', 'Other Item')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_value', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('imei_number', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='lost_items/images/')),
                ('ownership_bill', models.FileField(blank=True, null=True, upload_to='lost_items/bills/')),
                ('lost_date', models.DateField()),
                ('lost_time', models.TimeField(blank=True, null=True)),
                ('lost_place_text', models.CharField(max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('alternate_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('reward_note', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
