# Generated by Django 6.0.2 on 2026-03-12 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitemreport',
            name='status',
            field=models.CharField(choices=[('not_found', 'Not Found'), ('found', 'Found'), ('closed', 'Closed')], default='not_found', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitemreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FoundItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('mobile', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('earbuds', 'Earbuds / Headphones'), ('watch', 'Watch / Smartwatch'), ('wallet', 'Wallet / Purse'), ('bag', 'Bag'), ('id_card', 'ID Card / Certificate'), ('keys', 'Keys'), ('jewellery', 'Jewellery'), ('vehicle', 'Vehicle'), ('document', 'Document'), ('electronics', 'Other Electronics'), ('other', 'Other Item')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='found_items/images/')),
                ('found_date', models.DateField()),
                ('found_time', models.TimeField(blank=True, null=True)),
                ('found_place_text', models.CharField(max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('finder_name', models.CharField(max_length=255)),
                ('finder_phone', models.CharField(max_length=20)),
                ('finder_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('matched', 'Matched'), ('returned', 'Returned')], default='unclaimed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('contacts_visible_after', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.founditemreport')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lostitemreport')),
            ],
        ),
    ]
