# Generated by Django 6.0.2 on 2026-03-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lostitemreport_status_lostitemreport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditemreport',
            name='extra_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditemreport',
            name='imei_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
