# Generated by Django 6.0.2 on 2026-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_founditemreport_extra_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('technical_issue', 'Technical Issue'), ('account_support', 'Account Support'), ('report_concern', 'Report Concern'), ('feedback', 'Feedback / Suggestion'), ('complaint', 'Complaint')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
