# Generated by Django 6.0.2 on 2026-03-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactcomplaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('match_alerts', models.BooleanField(default=True)),
                ('claim_updates', models.BooleanField(default=True)),
                ('contact_after_match', models.BooleanField(default=True)),
                ('hide_sensitive_details', models.BooleanField(default=True)),
                ('activity_logging', models.BooleanField(default=True)),
                ('otp_verification', models.BooleanField(default=True)),
                ('google_login_access', models.BooleanField(default=True)),
                ('login_alerts', models.BooleanField(default=True)),
                ('save_search_history', models.BooleanField(default=True)),
                ('save_report_drafts', models.BooleanField(default=True)),
                ('personalized_suggestions', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('ml', 'Malayalam'), ('ms', 'Malay'), ('hi', 'Hindi'), ('si', 'Sinhala')], default='en', max_length=10)),
                ('region', models.CharField(choices=[('India', 'India'), ('Sri Lanka', 'Sri Lanka'), ('Malaysia', 'Malaysia'), ('Singapore', 'Singapore'), ('Canada', 'Canada')], default='India', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
